title: Educational Platform for Artificial Intelligence Training
description: Platform by UBC Deep Learning and Natural Language Processing Group. 
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
